### ISSUE TITLE
Update crates.io and docs.rs 

### ISSUE THREAD

**Issue by danya02** [tialaramex/misfortunate#2]
At time of writing, the version published on crates.io and docs.rs is `1.0.0`, but the repo's `Cargo.toml` says `1.2.0`.
You may have forgotten to press `cargo publish`.

Also, there's some changes on the repo that are newer than the `Cargo.toml` changes. While I don't have a particular need for them right now, I think it might be a good idea to publish a release for those as well.

Perhaps set up a Github Action to publish a release whenever the `version` field on `Cargo.toml` changes?

**Comment by tialaramex** [comment]
The Github Action idea is something to consider for another time. I am doing some maintenance on these crates and just published 1.2.0, now I'm looking at some GitHub issues
